### ISSUE TITLE
Website spacing

### ISSUE THREAD

**Issue by jdknives** [kittycash/kittycash.com#42] opened 2018-04-04 12:50 UTC
![bildschirmfoto 2018-04-04 um 14 49 09](https://user-images.githubusercontent.com/36450093/38308452-71b8fb46-3817-11e8-8ca3-2867613e3e4d.png)

- [ ] fix the spacing (game not in line, logo not in line, tabs clustered in the middle)

**Comment by 128-95** [comment] 2018-04-04 13:14
Duplicate of #40

**Closed by 128-95** 2018-04-04 13:14 UTC
Labels: duplicate
